deploy_lambda:
  name: Deploy Lambda to AWS
  runs-on: ubuntu-latest
  needs: sonarqube
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Package AWS SAM Application
      run: sam build --template template.yml
    - name: Deploy AWS SAM Application
      run: sam deploy --template-file .aws-sam/build/template.yaml --stack-name billi9 --capabilities CAPABILITY_IAM
